// Intelligent Calendar System with Travel Time Blocking and Conflict Detection

import { determineTravelMethod } from "./travel-config";
import { calculateTravelCosts, type VenueLocation } from "./travel-calculator";

export type EventCategory =
  | "professional_booking"
  | "personal_block"
  | "travel_block"
  | "practice"
  | "rehearsal";

export type BlockType = "hard" | "soft";

export interface CalendarEvent {
  id: string;
  title: string;
  description?: string;
  startDate: Date;
  endDate: Date;
  allDay: boolean;
  category: EventCategory;
  blockType: BlockType;
  color?: string;
  // Booking-specific fields
  bookingId?: string;
  venueLocation?: VenueLocation;
  // Travel-related fields
  relatedEventId?: string; // For travel blocks
  travelType?: "departure" | "return";
  // Metadata
  isAutoGenerated?: boolean;
  canOverride?: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface TravelWindow {
  departureDate: Date;
  departureTime: string;
  arrivalDate: Date;
  arrivalTime: string;
  blockReason: string;
}

export interface AvailabilityResult {
  isAvailable: boolean;
  reason?: string;
  conflictingEvents?: CalendarEvent[];
  travelConflict?: boolean;
  personalBlockConflict?: boolean;
  suggestedAlternatives?: Date[];
}

export interface ConflictCheckResult {
  hasConflict: boolean;
  conflictType?: "event" | "travel" | "personal" | "buffer";
  conflictingEvents: CalendarEvent[];
  message: string;
}

// Keywords that identify personal time blocks
const PERSONAL_KEYWORDS = [
  "personal",
  "family",
  "vacation",
  "off",
  "block",
  "private",
  "doctor",
  "appointment",
  "birthday",
  "anniversary",
  "holiday",
  "day off",
  "time off",
];

// Keywords that identify soft blocks (can be overridden)
const SOFT_BLOCK_KEYWORDS = ["practice", "rehearsal", "lesson", "maybe", "tentative"];

// Parse event title to determine category
export function categorizeEvent(title: string, color?: string): {
  category: EventCategory;
  blockType: BlockType;
} {
  const lowerTitle = title.toLowerCase();

  // Check for personal blocks
  if (PERSONAL_KEYWORDS.some((keyword) => lowerTitle.includes(keyword))) {
    return { category: "personal_block", blockType: "hard" };
  }

  // Check for soft blocks
  if (SOFT_BLOCK_KEYWORDS.some((keyword) => lowerTitle.includes(keyword))) {
    if (lowerTitle.includes("practice")) {
      return { category: "practice", blockType: "soft" };
    }
    if (lowerTitle.includes("rehearsal")) {
      return { category: "rehearsal", blockType: "soft" };
    }
  }

  // Color-based detection (red = hard block, orange = soft block)
  if (color === "red" || color === "#ff0000" || color === "#dc2626") {
    return { category: "personal_block", blockType: "hard" };
  }
  if (color === "orange" || color === "#f97316") {
    return { category: "practice", blockType: "soft" };
  }

  // Default to professional booking
  return { category: "professional_booking", blockType: "hard" };
}

// Calculate travel time blocks for an event
export function calculateTravelBlocks(
  event: CalendarEvent,
  distanceMiles: number
): { preEvent: TravelWindow | null; postEvent: TravelWindow | null } {
  const travelMethod = determineTravelMethod(distanceMiles);

  let preEventHours = 0;
  let postEventHours = 0;

  switch (travelMethod.method) {
    case "ground":
      // Local events: drive time + 30 min buffer
      preEventHours = Math.ceil(travelMethod.estimatedDriveTime / 60) + 0.5;
      postEventHours = Math.ceil(travelMethod.estimatedDriveTime / 60) + 0.5;
      break;

    case "ground_or_flight":
      // Regional: 3-4 hours for flight logistics or drive time
      if (distanceMiles > 150) {
        preEventHours = 5; // Airport arrival + flight + ground
        postEventHours = 4;
      } else {
        preEventHours = Math.ceil(travelMethod.estimatedDriveTime / 60) + 1;
        postEventHours = Math.ceil(travelMethod.estimatedDriveTime / 60) + 1;
      }
      break;

    case "flight_required":
      // Cross-country: full day before for 500+ miles
      if (distanceMiles > 500) {
        preEventHours = 24; // Day before
        postEventHours = 12; // Morning after for return
      } else {
        preEventHours = 6; // Regional flight
        postEventHours = 6;
      }
      break;
  }

  // Calculate pre-event travel window
  const preEventStart = new Date(event.startDate);
  preEventStart.setHours(preEventStart.getHours() - preEventHours);

  const preEventEnd = new Date(event.startDate);
  preEventEnd.setMinutes(preEventEnd.getMinutes() - 30); // 30 min buffer before event

  const preEventWindow: TravelWindow = {
    departureDate: preEventStart,
    departureTime: preEventStart.toTimeString().slice(0, 5),
    arrivalDate: preEventEnd,
    arrivalTime: preEventEnd.toTimeString().slice(0, 5),
    blockReason: `Travel to ${event.title}`,
  };

  // Calculate post-event travel window
  const postEventStart = new Date(event.endDate);
  postEventStart.setMinutes(postEventStart.getMinutes() + 30); // 30 min buffer after event

  const postEventEnd = new Date(event.endDate);
  postEventEnd.setHours(postEventEnd.getHours() + postEventHours);

  const postEventWindow: TravelWindow = {
    departureDate: postEventStart,
    departureTime: postEventStart.toTimeString().slice(0, 5),
    arrivalDate: postEventEnd,
    arrivalTime: postEventEnd.toTimeString().slice(0, 5),
    blockReason: `Return from ${event.title}`,
  };

  return {
    preEvent: preEventHours > 0 ? preEventWindow : null,
    postEvent: postEventHours > 0 ? postEventWindow : null,
  };
}

// Create travel block events
export function createTravelBlockEvents(
  mainEvent: CalendarEvent,
  preEventWindow: TravelWindow | null,
  postEventWindow: TravelWindow | null
): CalendarEvent[] {
  const travelBlocks: CalendarEvent[] = [];

  if (preEventWindow) {
    travelBlocks.push({
      id: `travel-pre-${mainEvent.id}`,
      title: preEventWindow.blockReason,
      startDate: preEventWindow.departureDate,
      endDate: preEventWindow.arrivalDate,
      allDay: false,
      category: "travel_block",
      blockType: "hard",
      relatedEventId: mainEvent.id,
      travelType: "departure",
      isAutoGenerated: true,
      canOverride: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  if (postEventWindow) {
    travelBlocks.push({
      id: `travel-post-${mainEvent.id}`,
      title: postEventWindow.blockReason,
      startDate: postEventWindow.departureDate,
      endDate: postEventWindow.arrivalDate,
      allDay: false,
      category: "travel_block",
      blockType: "hard",
      relatedEventId: mainEvent.id,
      travelType: "return",
      isAutoGenerated: true,
      canOverride: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  return travelBlocks;
}

// Check if two time ranges overlap
function timeRangesOverlap(
  start1: Date,
  end1: Date,
  start2: Date,
  end2: Date
): boolean {
  return start1 < end2 && start2 < end1;
}

// Check for conflicts with existing calendar events
export function checkConflicts(
  proposedStart: Date,
  proposedEnd: Date,
  existingEvents: CalendarEvent[],
  includeTravel: boolean = true,
  includeSoftBlocks: boolean = false
): ConflictCheckResult {
  const conflictingEvents: CalendarEvent[] = [];
  let conflictType: ConflictCheckResult["conflictType"];
  let message = "";

  for (const event of existingEvents) {
    // Skip soft blocks if not included
    if (!includeSoftBlocks && event.blockType === "soft") {
      continue;
    }

    // Check overlap
    if (timeRangesOverlap(proposedStart, proposedEnd, event.startDate, event.endDate)) {
      conflictingEvents.push(event);

      // Determine conflict type
      if (event.category === "professional_booking") {
        conflictType = "event";
        message = `Conflicts with existing booking: ${event.title}`;
      } else if (event.category === "travel_block" && includeTravel) {
        conflictType = "travel";
        message = `Conflicts with travel time for: ${event.title}`;
      } else if (event.category === "personal_block") {
        conflictType = "personal";
        message = `Conflicts with personal time: ${event.title}`;
      }
    }
  }

  return {
    hasConflict: conflictingEvents.length > 0,
    conflictType,
    conflictingEvents,
    message,
  };
}

// Check full availability including travel windows
export function checkAvailability(
  eventDate: Date,
  eventStartTime: string,
  eventEndTime: string,
  venueLocation: VenueLocation,
  existingEvents: CalendarEvent[],
  currentHomeBase: string = "nashville"
): AvailabilityResult {
  const [startHour, startMin] = eventStartTime.split(":").map(Number);
  const [endHour, endMin] = eventEndTime.split(":").map(Number);

  const eventStart = new Date(eventDate);
  eventStart.setHours(startHour, startMin, 0, 0);

  const eventEnd = new Date(eventDate);
  eventEnd.setHours(endHour, endMin, 0, 0);

  // Calculate travel costs to get distances and travel requirements
  const travelCosts = calculateTravelCosts({
    venueLocation,
    eventDate,
    eventStartTime,
    eventEndTime,
    eventDuration: (endHour - startHour) * 60 + (endMin - startMin),
    currentHomeBase,
  });

  // Create temporary event for travel block calculation
  const tempEvent: CalendarEvent = {
    id: "temp",
    title: "Proposed Event",
    startDate: eventStart,
    endDate: eventEnd,
    allDay: false,
    category: "professional_booking",
    blockType: "hard",
    venueLocation,
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  // Calculate travel blocks
  const travelBlocks = calculateTravelBlocks(
    tempEvent,
    travelCosts.travelMethod.distanceMiles
  );

  // Determine full window to check
  let fullWindowStart = eventStart;
  let fullWindowEnd = eventEnd;

  if (travelBlocks.preEvent) {
    fullWindowStart = travelBlocks.preEvent.departureDate;
  }
  if (travelBlocks.postEvent) {
    fullWindowEnd = travelBlocks.postEvent.arrivalDate;
  }

  // Check for conflicts across full window
  const conflictResult = checkConflicts(
    fullWindowStart,
    fullWindowEnd,
    existingEvents,
    true,
    false
  );

  if (conflictResult.hasConflict) {
    const suggestedAlternatives = findAlternativeDates(
      eventDate,
      eventStartTime,
      eventEndTime,
      venueLocation,
      existingEvents,
      currentHomeBase
    );

    return {
      isAvailable: false,
      reason: conflictResult.message,
      conflictingEvents: conflictResult.conflictingEvents,
      travelConflict: conflictResult.conflictType === "travel",
      personalBlockConflict: conflictResult.conflictType === "personal",
      suggestedAlternatives,
    };
  }

  return {
    isAvailable: true,
  };
}

// Find alternative available dates
export function findAlternativeDates(
  originalDate: Date,
  startTime: string,
  endTime: string,
  venueLocation: VenueLocation,
  existingEvents: CalendarEvent[],
  currentHomeBase: string,
  searchDays: number = 14
): Date[] {
  const alternatives: Date[] = [];

  for (let i = -searchDays; i <= searchDays; i++) {
    if (i === 0) continue; // Skip original date

    const checkDate = new Date(originalDate);
    checkDate.setDate(checkDate.getDate() + i);

    // Skip past dates
    if (checkDate < new Date()) continue;

    const availability = checkAvailability(
      checkDate,
      startTime,
      endTime,
      venueLocation,
      existingEvents,
      currentHomeBase
    );

    if (availability.isAvailable) {
      alternatives.push(checkDate);
    }

    // Limit to 5 suggestions
    if (alternatives.length >= 5) break;
  }

  return alternatives;
}

// Detect travel clustering opportunities
export interface ClusterOpportunity {
  events: CalendarEvent[];
  region: string;
  dateRange: { start: Date; end: Date };
  potentialSavings: number;
  recommendation: string;
}

export function detectTravelClustering(
  events: CalendarEvent[]
): ClusterOpportunity[] {
  const opportunities: ClusterOpportunity[] = [];

  // Group events by region (simplified - would use geocoding in production)
  const eventsByRegion: Record<string, CalendarEvent[]> = {};

  for (const event of events) {
    if (event.venueLocation) {
      const region = `${event.venueLocation.state}`;
      if (!eventsByRegion[region]) {
        eventsByRegion[region] = [];
      }
      eventsByRegion[region].push(event);
    }
  }

  // Find clusters (events within 3 days of each other in same region)
  for (const [region, regionEvents] of Object.entries(eventsByRegion)) {
    if (regionEvents.length < 2) continue;

    // Sort by date
    const sorted = regionEvents.sort(
      (a, b) => a.startDate.getTime() - b.startDate.getTime()
    );

    for (let i = 0; i < sorted.length - 1; i++) {
      const current = sorted[i];
      const next = sorted[i + 1];

      const daysBetween = Math.ceil(
        (next.startDate.getTime() - current.startDate.getTime()) / (1000 * 60 * 60 * 24)
      );

      if (daysBetween <= 3) {
        // Estimate savings (one round trip vs two)
        const potentialSavings = 400; // Estimated savings from consolidated travel

        opportunities.push({
          events: [current, next],
          region,
          dateRange: {
            start: current.startDate,
            end: next.endDate,
          },
          potentialSavings,
          recommendation: `Consider staying in ${region} between events to save approximately $${potentialSavings} in travel costs.`,
        });
      }
    }
  }

  return opportunities;
}

// Get availability display status for client calendar
export function getAvailabilityDisplay(
  date: Date,
  events: CalendarEvent[]
): {
  status: "available" | "booked" | "unavailable" | "partial";
  reason?: string;
} {
  // Check events on this date
  const dateStart = new Date(date);
  dateStart.setHours(0, 0, 0, 0);

  const dateEnd = new Date(date);
  dateEnd.setHours(23, 59, 59, 999);

  const dayEvents = events.filter(
    (event) =>
      (event.startDate >= dateStart && event.startDate <= dateEnd) ||
      (event.endDate >= dateStart && event.endDate <= dateEnd) ||
      (event.startDate <= dateStart && event.endDate >= dateEnd)
  );

  // No events - available
  if (dayEvents.length === 0) {
    return { status: "available" };
  }

  // Check for full-day blocks
  const fullDayBlocks = dayEvents.filter(
    (event) =>
      event.allDay ||
      (event.startDate <= dateStart && event.endDate >= dateEnd)
  );

  if (fullDayBlocks.length > 0) {
    const firstBlock = fullDayBlocks[0];
    if (firstBlock.category === "professional_booking") {
      return { status: "booked", reason: "Booked" };
    }
    return { status: "unavailable", reason: "Unavailable" };
  }

  // Check for professional bookings
  const bookings = dayEvents.filter(
    (event) => event.category === "professional_booking"
  );

  if (bookings.length > 0) {
    return { status: "booked", reason: "Booked" };
  }

  // Personal or travel blocks
  const blocks = dayEvents.filter(
    (event) =>
      event.category === "personal_block" || event.category === "travel_block"
  );

  if (blocks.length > 0) {
    return { status: "unavailable", reason: "Unavailable" };
  }

  // Soft blocks - partial availability
  return { status: "partial", reason: "Limited availability" };
}

// Calculate minimum rest period between events
export function validateRestPeriod(
  event1End: Date,
  event2Start: Date,
  minimumHours: number = 12
): boolean {
  const hoursBetween =
    (event2Start.getTime() - event1End.getTime()) / (1000 * 60 * 60);
  return hoursBetween >= minimumHours;
}
