import { NextResponse } from "next/server";
import {
  checkAvailability,
  getAvailabilityDisplay,
  type CalendarEvent,
} from "@/lib/calendar-intelligence";

// Mock calendar events (in production, fetch from database or Google Calendar API)
const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "booking-1",
    title: "Thompson Wedding",
    startDate: new Date("2024-09-15T16:00:00"),
    endDate: new Date("2024-09-15T21:00:00"),
    allDay: false,
    category: "professional_booking",
    blockType: "hard",
    venueLocation: {
      address: "123 Grand Ave",
      city: "Atlanta",
      state: "GA",
    },
    bookingId: "VB-ABC123",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "travel-pre-1",
    title: "Travel to Thompson Wedding",
    startDate: new Date("2024-09-15T10:00:00"),
    endDate: new Date("2024-09-15T15:30:00"),
    allDay: false,
    category: "travel_block",
    blockType: "hard",
    relatedEventId: "booking-1",
    travelType: "departure",
    isAutoGenerated: true,
    canOverride: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "personal-1",
    title: "Family vacation",
    startDate: new Date("2024-10-01T00:00:00"),
    endDate: new Date("2024-10-07T23:59:59"),
    allDay: true,
    category: "personal_block",
    blockType: "hard",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const month = searchParams.get("month");
  const year = searchParams.get("year");

  if (!month || !year) {
    return NextResponse.json(
      { error: "Month and year are required" },
      { status: 400 }
    );
  }

  const monthNum = parseInt(month);
  const yearNum = parseInt(year);

  // Generate availability for each day of the month
  const daysInMonth = new Date(yearNum, monthNum, 0).getDate();
  const availability: Record<
    string,
    { status: string; reason?: string }
  > = {};

  for (let day = 1; day <= daysInMonth; day++) {
    const date = new Date(yearNum, monthNum - 1, day);
    const dateKey = date.toISOString().split("T")[0];

    // Don't show past dates as available
    if (date < new Date()) {
      availability[dateKey] = { status: "unavailable", reason: "Past date" };
      continue;
    }

    const dayStatus = getAvailabilityDisplay(date, mockCalendarEvents);
    availability[dateKey] = dayStatus;
  }

  return NextResponse.json({
    success: true,
    month: monthNum,
    year: yearNum,
    availability,
  });
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      eventDate,
      eventStartTime,
      eventEndTime,
      venueCity,
      venueState,
      currentHomeBase,
    } = body;

    if (!eventDate || !eventStartTime || !venueCity || !venueState) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    const result = checkAvailability(
      new Date(eventDate),
      eventStartTime,
      eventEndTime || "20:00",
      {
        address: "",
        city: venueCity,
        state: venueState,
      },
      mockCalendarEvents,
      currentHomeBase || "nashville"
    );

    return NextResponse.json({
      success: true,
      available: result.isAvailable,
      reason: result.reason,
      travelConflict: result.travelConflict,
      personalBlockConflict: result.personalBlockConflict,
      suggestedAlternatives: result.suggestedAlternatives?.map((d) =>
        d.toISOString().split("T")[0]
      ),
      conflictingEvents: result.conflictingEvents?.map((e) => ({
        title: e.title,
        date: e.startDate.toISOString(),
        category: e.category,
      })),
    });
  } catch (error) {
    console.error("Availability check error:", error);
    return NextResponse.json(
      { error: "Failed to check availability" },
      { status: 500 }
    );
  }
}
